
set nocompatible

syntax on

set shell=bash
if has("gui_win32")
    set packpath+=$HOME/.vim/
    set guifont=Consolas:h12:cANSI
    "set guioptions-=m  "menu bar
    set guioptions-=T  "toolbar
    set guioptions-=r  "scrollbarset
    :simalt ~x          "maximized window
endif


" show end of line, see: https://stackoverflow.com/questions/3860519/see-line-breaks-and-carriage-returns-in-editor
set ffs=unix
set encoding=utf-8
set fileencoding=utf-8
"set listchars=eol:¶
"set list


" setup solarived8 color scheme
:packadd solarized8
set background=dark
colorscheme solarized8


let mapleader = " "
set clipboard=unnamed
set backspace=indent,eol,start
set showmode
set tabstop=4
set expandtab


" ui layout
set laststatus=2
set showcmd
set nocursorline
set showmatch " highlight matching parenthesis

" turn hybrid line numbers on, see: https://jeffkreeftmeijer.com/vim-number/
set nu rnu


" searching
set ignorecase
set incsearch  " search as chars are entered
set hlsearch   " highlight all matches


" disable recording for now
map q <nop>

" remap to 0 to first non-blank char
map 0 ^ 

" arrows are unvimlike
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>


" fast saving
nmap <leader>w :w!<cr>


" edit/reload vimrc config file
nnoremap <leader>ve :e ~/.vimrc<cr>
nnoremap <leader>vr :so ~/.vimrc<cr>

nnoremap <leader>help :vert help<cr>

" windows management, see: https://thoughtbot.com/blog/vim-splits-move-faster-and-more-naturally
set splitright

map <C-h> <C-W>h
map <C-l> <C-W>l
map <leader>h :bprevious<cr>
map <leader>l :bnext<cr>


" disable swapfiles
set noswapfile
